<?php																				// LOOPS AND IF STATEMENTS ARE SOME OF THE FUNDAMENTAL WAYS OF AFFECTING THE FLOW OF CODE AND ARE VITAL FOR MODERN-DAY PROGRAMMING (e.g. AN EMAIL CLIENT DISPLAYING EMAILS - LOOPING THROUGH ALL EMAILS IN A DATABASE THEN DISPLAYING THEM TO USER)
	for ($i = 0; $i < 10; $i++) {  						// SIMILAR TO JS - DECLARING AND INITIALISING COUNTER VARIABLE (INITIAL VALUE OF 0), THEN SETTING CONDITIONS FOR THE FOR LOOP TO CONTINUE (HERE, KEEP PARSING AS LONG AS THE VALUE OF i IS LESS THAN 10), THEN SETTING THE RULE FOR WHAT OCCURS EACH TIME THE LOOP IS PARSED (HERE, INCREMENT THE VALUE OF i)
		echo $i."<br>" 													// ie. DISPLAY THE CONTENTS OF i WITH EACH SUCCESSIVE LOOP
	}

																						// LINE 2 DEFINES THE LOOP. LINE 3 DEFINES THE OUTPUT/CODE TO PARSE EVERY TIME THE CONDITION IS MET

?>