<?php
// POST VARIABLES WORK SIMILAR TO GET VARIABLES, BUT AREN'T ENCODED IN THE URL. THIS MAKES THEM MORE SECURE.
// POST VARIABLES CAN ALSO BE PASSED CERTAIN CHARACTERS TO VARIABLES WHICH WON'T RETURN ERRORS, UNLIKE GET


?>